name: CI
on: [pull_request]
jobs:
  test-skip-install-and-use-bundler:
    name: runner / brakeman
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/using_gemfile
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/test/using_gemfile/Gemfile
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: install brakeman with version written in Gemfile.lock
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          brakeman_version: 'gemfile'
          brakeman_flags: '--force'
      - run: |
          test "$(bundle exec brakeman --version)" == "brakeman 5.1.2"
